FROM node:8 as build-step
COPY . /workdir
WORKDIR /workdir
RUN yarn build

FROM nginx:stable-alpine

LABEL vendor="IntelliFarms" \
  team="WebDev"

COPY config/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-step /workdir/build /usr/share/nginx/html
