version: "3"

services:
  ingress:
    ports:
      - "4000:80"
    build:
      context: ./ingress
      dockerfile: Dockerfile
    links:
      - frontend
      - graphql
    restart: always
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/app"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
    ports:
      - "5500:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  graphql:
    build:
      context: ./graphql
      dockerfile: Dockerfile
    ports:
      - "9002:9229"
    volumes:
      - "./graphql:/app"
    restart: always
    links:
      - db
volumes:
  pgdata:
